### ISSUE TITLE
Add TextArea component

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/fuel-ui#7]
## Tasks

- [ ] `TextArea` component
- [ ] Tests Scenarios

## Description

The Textarea component allows you to easily create multi-line text inputs.

## Usage

```jsx
import { TextArea } from '@fuel-js/react';

/**
 * Basic example
 */
export default () => (
  <TextArea placeholder='Here is a sample placeholder' />
);
```

#### `<TextArea />`

- `value: string`
- `defaultValue: string`
- `onChange: (value: string) => void`
- `isInvalid: boolean`
- `isRequired: boolean`
- `isDisabled: boolean`
- `isLoading: boolean`
- `isReadOnly: boolean`

## References

- Heavily inspired on [Chakra's TextArea](https://chakra-ui.com/docs/components/form/textarea)
<img width="783" alt="Screen Shot 2022-05-02 at 12 37 51" src="https://user-images.githubusercontent.com/2029172/166262973-1b7623ff-c780-4495-8204-c42c365bfefe.png">

## Tests Scenarios

- [ ] Should render a basic `<textarea />` component
- [ ] Should call onChange on value change
- [ ] Should derive values from surrounding `Form.Control`
